# Generated by Django 5.2.8 on 2025-11-08 03:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Juiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Jogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campeonato', models.CharField(choices=[('Brasileiro: Série A', 'Brasileiro: Série A'), ('Brasileiro: Série B', 'Brasileiro: Série B'), ('Premier League', 'Premier League'), ('La Liga', 'La Liga'), ('Bundesliga', 'Bundesliga'), ('Italiano: Serie A', 'Italiano: Serie A'), ('Ligue 1', 'Ligue 1')], max_length=50)),
                ('rodada', models.IntegerField()),
                ('estadio', models.CharField(blank=True, max_length=100, null=True)),
                ('data', models.DateField()),
                ('resultado', models.CharField(blank=True, choices=[('M', 'Mandante'), ('V', 'Visitante'), ('E', 'Empate')], max_length=1, null=True)),
                ('gols_mandante', models.IntegerField()),
                ('gols_visitante', models.IntegerField()),
                ('faltas_mandante', models.IntegerField(blank=True, null=True)),
                ('faltas_visitante', models.IntegerField(blank=True, null=True)),
                ('cartoes_mandante', models.IntegerField(blank=True, null=True)),
                ('cartoes_visitante', models.IntegerField(blank=True, null=True)),
                ('escanteios_mandante', models.IntegerField(blank=True, null=True)),
                ('escanteios_visitante', models.IntegerField(blank=True, null=True)),
                ('posse_bola_mandante', models.FloatField(blank=True, null=True)),
                ('posse_bola_visitante', models.FloatField(blank=True, null=True)),
                ('publico', models.IntegerField(blank=True, null=True)),
                ('chutes_mandante', models.IntegerField(blank=True, null=True)),
                ('chutes_visitante', models.IntegerField(blank=True, null=True)),
                ('juiz', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='form.juiz')),
                ('mandante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jogos_mandante', to='form.time')),
                ('visitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jogos_visitante', to='form.time')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('campeonato', 'data', 'mandante', 'visitante'), name='unique_jogo')],
            },
        ),
    ]
