# Generated by Django 5.2.8 on 2025-11-08 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jogo',
            name='estadio',
        ),
        migrations.AlterField(
            model_name='jogo',
            name='campeonato',
            field=models.CharField(choices=[('Brasileiro: Série A', 'Brasileiro: Série A'), ('Brasileiro: Série B', 'Brasileiro: Série B'), ('Bundesliga', 'Bundesliga'), ('Italiano: Serie A', 'Italiano: Serie A'), ('La Liga', 'La Liga'), ('Ligue 1', 'Ligue 1'), ('Premier League', 'Premier League')], max_length=50),
        ),
    ]
