# Generated by Django 5.2.8 on 2025-11-08 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0002_remove_jogo_estadio_alter_jogo_campeonato'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='juiz',
            options={'ordering': ['nome']},
        ),
        migrations.AlterModelOptions(
            name='time',
            options={'ordering': ['nome']},
        ),
        migrations.AlterModelTable(
            name='juiz',
            table='juizes',
        ),
    ]
