# Generated by Django 5.2.8 on 2025-11-08 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0003_alter_juiz_options_alter_time_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='juiz',
            options={'ordering': ['nome'], 'verbose_name': 'Juiz', 'verbose_name_plural': 'Juízes'},
        ),
    ]
