# Generated by Django 5.2.8 on 2025-12-20 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('dashboard_html', models.FileField(blank=True, null=True, upload_to='dashboards/')),
            ],
        ),
    ]
